---
- name: Copy site content files.
  copy:
    src: "{{ item.site_content }}"
    dest: "{{ item.root }}/{{ item.site_content }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: '0644'
  when: item.site_content is defined
  with_items: "{{ nginx_vhosts }}"
