---
- name: restart php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
    enabled: "{{ php_fpm_enabled_at_boot }}"
  listen: "restart php-fpm"

- name: restart webserver
  service:
    name: "{{ php_webserver_daemon }}"
    state: restarted
  when: php_enable_webserver