---
- name: Delete OpCache ini file if this role will provide one.
  file:
    path: "{{ php_extension_conf_path }}/{{ php_opcache_conf_filename }}"
    state: absent
  when: php_opcache_enable and php_package_install.changed

- name: Check for existing OpCache config files.
  find:
    paths: "/etc/php/{{ php_default_version }}/fpm/conf.d"
    contains: 'zend_extension(\s+)?=(\s+)?opcache\.so'
  register: old_opcache_inis

- name: Remove any non-role-supplied OpCache config files.
  file:
    path: "{{ item.path }}"
    state: absent
  when: php_opcache_conf_filename != (item.path.split('/') | last)
  with_items: "{{ old_opcache_inis.files }}"

- name: Ensure OpCache config file is present.
  template:
    src: opcache.ini.j2
    dest: "{{ php_extension_conf_path }}/{{ php_opcache_conf_filename }}"
    owner: root
    group: root
    force: true
    mode: 0644
  when: php_opcache_enable
  notify: restart php-fpm
