---
- name: Ensure configuration directories exist.
  file:
    path: "{{ item }}"
    state: directory
    follow: true
  with_items:
    - "{{ php_fpm_conf_path }}"
    - "{{ php_extension_conf_path }}"

- name: Place PHP configuration file in place.
  template:
    src: php.ini.j2
    dest: "{{ php_fpm_conf_path }}/php.ini"
    owner: root
    group: root
    mode: 0644
  when: php_use_managed_ini
