---
# Variable setup.
- name: platform specific variables
  include_vars: "{{ php_fpm_deployment_platform }}.yml"

- name: Include package and resource path variables.
  include_vars: "bionic.yml"

- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

# - name: Define extra php_packages.
#   set_fact:
#     php_packages: "{{ php_packages | list + php_packages_extra | list }}"
#   when: php_packages_extra is defined

- name: Define php_webserver_daemon.
  set_fact:
    php_webserver_daemon: "{{ __php_webserver_daemon }}"
  when: php_webserver_daemon is not defined

- name: Define php_fpm_conf_path.
  set_fact:
    php_fpm_conf_path: "{{ __php_fpm_conf_path }}"
  when: php_fpm_conf_path is not defined

- name: Define php_extension_conf_path.
  set_fact:
    php_extension_conf_path: "{{ __php_extension_conf_path }}"
  when: php_extension_conf_path is not defined

- name: Define php_opcache_conf_filename.
  set_fact:
    php_opcache_conf_filename: "{{ __php_opcache_conf_filename }}"
  when: php_opcache_conf_filename is not defined

- include_tasks: install-packages.yml

# Configure PHP.
- include_tasks: configure.yml
- include_tasks: configure-opcache.yml
- include_tasks: configure-fpm.yml
