---
# php-fpm enabled at boot up
php_fpm_enabled_at_boot: true

# ; Miscellaneous ;
php_expose_php: "Off"
# ; Error handling and logging ;
php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_display_errors: "Off"
php_display_startup_errors: "Off"
# ; File Uploads ;
php_file_uploads: "Off"