---
- name: Add PPA for certbot.
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present
    update_cache: true
  when: add_certbot_ppa | bool

- name: Install Certbot.
  package: "name={{ certbot_package }} state=present"

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_package }}"
